package com.taskflow.dto.request;

import com.taskflow.entity.Priority;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.time.LocalDate;

/**
 * DTO for creating a new project.
 *
 * WHAT THE CLIENT SENDS (JSON body):
 * {
 *   "name": "TaskFlow App",
 *   "description": "A project management system",
 *   "priority": "HIGH",
 *   "startDate": "2026-06-01",
 *   "targetEndDate": "2026-12-01"
 * }
 *
 * WHAT WE DON'T INCLUDE HERE:
 *   - id         → generated by DB
 *   - status     → always starts as PLANNING
 *   - owner      → set from JWT token (the logged-in user IS the owner)
 *   - members    → start with no members (added separately via add-member API)
 *   - createdAt  → set by @PrePersist
 *
 * SECURITY: owner is NOT in the request body.
 * If it were, a client could say "ownerId: 999" and forge ownership.
 * Instead, we read the owner from the JWT token (the authenticated user).
 */
@Data
public class CreateProjectRequest {

    @NotBlank(message = "Project name is required")
    @Size(min = 2, max = 200, message = "Project name must be between 2 and 200 characters")
    private String name;

    @Size(max = 2000, message = "Description cannot exceed 2000 characters")
    private String description;

    private Priority priority;         // Optional — defaults to MEDIUM in service

    private LocalDate startDate;       // Optional

    private LocalDate targetEndDate;   // Optional — the planned completion date
}
