package com.taskflow.dto.request;

import com.taskflow.entity.Priority;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.time.LocalDate;

/**
 * DTO for creating a new task inside a project.
 *
 * WHAT THE CLIENT SENDS:
 * {
 *   "title": "Implement login page",
 *   "description": "Design the login form with email + password fields",
 *   "priority": "HIGH",
 *   "dueDate": "2026-07-01",
 *   "estimatedHours": 8,
 *   "projectId": 1,
 *   "assigneeId": 5
 * }
 *
 * WHAT WE DON'T INCLUDE:
 *   - id          → generated by DB
 *   - status      → always starts as TODO
 *   - reporterId  → set from JWT token (the person creating the task IS the reporter)
 *   - createdAt   → @PrePersist
 *   - actualHours → filled later when task is completed
 */
@Data
public class CreateTaskRequest {

    @NotBlank(message = "Task title is required")
    @Size(min = 2, max = 300, message = "Title must be between 2 and 300 characters")
    private String title;

    @Size(max = 5000, message = "Description cannot exceed 5000 characters")
    private String description;

    private Priority priority;    // Optional — defaults to MEDIUM in service

    private LocalDate dueDate;    // Optional

    @Min(value = 1, message = "Estimated hours must be at least 1")
    private Integer estimatedHours;  // Optional — how long we think it'll take

    @NotNull(message = "Project ID is required")
    private Long projectId;      // Which project this task belongs to

    private Long assigneeId;     // Optional — who will do the work (can assign later)
}
